name = "img-delivery-bridge-api"
main = "src/index.js"
compatibility_date = "2026-09-08"

[[d1_databases]]
binding = "DB"
database_name = "img-delivery-bridge"
database_id = "REPLACE_WITH_D1_DATABASE_ID"
